"""empty message

Revision ID: bcb63cea1e9f
Revises: 5718bd3352a7
Create Date: 2020-07-19 23:59:43.632572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb63cea1e9f'
down_revision = '5718bd3352a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('Shows', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
